-- 00XX_threepp_compendium.sql  (generated by threepp.mjs ddl — DO NOT hand-edit; regenerate)
-- 18 3pp tables on the PFcore compendium contract (public read · service write · tsvector+GIN).
-- Search RPCs are emitted separately by `threepp.mjs rpc` (0026 prefix/substring pattern).

create table if not exists public.psionic_power_compendium (
  slug text primary key,
  "name" text,
  "discipline" text,
  "descriptors" text,
  "display" text,
  "manifesting_time" text,
  "range" text,
  "target_area_effect" text,
  "duration" text,
  "saving_throw" text,
  "power_resistance" text,
  "power_points" text,
  "description" text,
  "augment" text,
  "special" text,
  "mythic" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("description",'') || ' ' || coalesce("augment",''))) stored
);
create index if not exists psionic_power_compendium_search_idx on public.psionic_power_compendium using gin (search);
alter table public.psionic_power_compendium enable row level security;
create policy "psionic_power_compendium_public_read" on public.psionic_power_compendium for select to anon, authenticated using (true);
create policy "psionic_power_compendium_service_write" on public.psionic_power_compendium for all to service_role using (true) with check (true);


create table if not exists public.psionic_power_class_level (
  "power" text,
  "class" text,
  "level" text,
  "source" text,
  "url" text,
  primary key ("power", "class")
);
create index if not exists psionic_power_class_level_power_idx on public.psionic_power_class_level ("power");
create index if not exists psionic_power_class_level_class_idx on public.psionic_power_class_level ("class");
alter table public.psionic_power_class_level enable row level security;
create policy "psionic_power_class_level_public_read" on public.psionic_power_class_level for select to anon, authenticated using (true);
create policy "psionic_power_class_level_service_write" on public.psionic_power_class_level for all to service_role using (true) with check (true);


create table if not exists public.pow_discipline_compendium (
  slug text primary key,
  "name" text,
  "associated_skill" text,
  "associated_weapon_groups" text,
  "martial_tradition" text,
  "title_veil" text,
  "dao_veil" text,
  "description" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists pow_discipline_compendium_search_idx on public.pow_discipline_compendium using gin (search);
alter table public.pow_discipline_compendium enable row level security;
create policy "pow_discipline_compendium_public_read" on public.pow_discipline_compendium for select to anon, authenticated using (true);
create policy "pow_discipline_compendium_service_write" on public.pow_discipline_compendium for all to service_role using (true) with check (true);


create table if not exists public.pow_maneuver_compendium (
  slug text primary key,
  "name" text,
  "discipline" text,
  "level" text,
  "category" text,
  "type" text,
  "descriptor" text,
  "initiation_action" text,
  "range" text,
  "target" text,
  "duration" text,
  "saving_throw" text,
  "prerequisite" text,
  "description" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists pow_maneuver_compendium_search_idx on public.pow_maneuver_compendium using gin (search);
create index if not exists pow_maneuver_compendium_discipline_idx on public.pow_maneuver_compendium ("discipline");
alter table public.pow_maneuver_compendium enable row level security;
create policy "pow_maneuver_compendium_public_read" on public.pow_maneuver_compendium for select to anon, authenticated using (true);
create policy "pow_maneuver_compendium_service_write" on public.pow_maneuver_compendium for all to service_role using (true) with check (true);


create table if not exists public.akashic_veil_compendium (
  slug text primary key,
  "name" text,
  "slot" text,
  "descriptors" text,
  "effect" text,
  "bind_effect" text,
  "is_retold" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("effect",'') || ' ' || coalesce("bind_effect",''))) stored
);
create index if not exists akashic_veil_compendium_search_idx on public.akashic_veil_compendium using gin (search);
alter table public.akashic_veil_compendium enable row level security;
create policy "akashic_veil_compendium_public_read" on public.akashic_veil_compendium for select to anon, authenticated using (true);
create policy "akashic_veil_compendium_service_write" on public.akashic_veil_compendium for all to service_role using (true) with check (true);


create table if not exists public.akashic_veil_class_list (
  "veil" text,
  "veil_list" text,
  "source" text,
  "url" text,
  primary key ("veil", "veil_list")
);
create index if not exists akashic_veil_class_list_veil_idx on public.akashic_veil_class_list ("veil");
create index if not exists akashic_veil_class_list_veil_list_idx on public.akashic_veil_class_list ("veil_list");
alter table public.akashic_veil_class_list enable row level security;
create policy "akashic_veil_class_list_public_read" on public.akashic_veil_class_list for select to anon, authenticated using (true);
create policy "akashic_veil_class_list_service_write" on public.akashic_veil_class_list for all to service_role using (true) with check (true);


create table if not exists public.threepp_feat_compendium (
  slug text primary key,
  "name" text,
  "type" text,
  "system" text,
  "prerequisites" text,
  "benefit" text,
  "normal" text,
  "special" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("type",'') || ' ' || coalesce("system",'') || ' ' || coalesce("benefit",'') || ' ' || coalesce("prerequisites",''))) stored
);
create index if not exists threepp_feat_compendium_search_idx on public.threepp_feat_compendium using gin (search);
alter table public.threepp_feat_compendium enable row level security;
create policy "threepp_feat_compendium_public_read" on public.threepp_feat_compendium for select to anon, authenticated using (true);
create policy "threepp_feat_compendium_service_write" on public.threepp_feat_compendium for all to service_role using (true) with check (true);


create table if not exists public.threepp_class_compendium (
  slug text primary key,
  "name" text,
  "class_type" text,
  "system" text,
  "alignment" text,
  "hit_die" text,
  "skill_points" text,
  "bab" text,
  "fort" text,
  "ref" text,
  "will" text,
  "class_features" text,
  "progression_json" jsonb,
  "description" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("system",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists threepp_class_compendium_search_idx on public.threepp_class_compendium using gin (search);
alter table public.threepp_class_compendium enable row level security;
create policy "threepp_class_compendium_public_read" on public.threepp_class_compendium for select to anon, authenticated using (true);
create policy "threepp_class_compendium_service_write" on public.threepp_class_compendium for all to service_role using (true) with check (true);


create table if not exists public.threepp_archetype_compendium (
  slug text primary key,
  "name" text,
  "base_class" text,
  "system" text,
  "altered_features" text,
  "description" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("base_class",'') || ' ' || coalesce("system",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists threepp_archetype_compendium_search_idx on public.threepp_archetype_compendium using gin (search);
create index if not exists threepp_archetype_compendium_base_class_idx on public.threepp_archetype_compendium ("base_class");
alter table public.threepp_archetype_compendium enable row level security;
create policy "threepp_archetype_compendium_public_read" on public.threepp_archetype_compendium for select to anon, authenticated using (true);
create policy "threepp_archetype_compendium_service_write" on public.threepp_archetype_compendium for all to service_role using (true) with check (true);


create table if not exists public.threepp_class_option_compendium (
  slug text primary key,
  "name" text,
  "base_class" text,
  "system" text,
  "option_type" text,
  "description" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("base_class",'') || ' ' || coalesce("option_type",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists threepp_class_option_compendium_search_idx on public.threepp_class_option_compendium using gin (search);
create index if not exists threepp_class_option_compendium_base_class_idx on public.threepp_class_option_compendium ("base_class");
alter table public.threepp_class_option_compendium enable row level security;
create policy "threepp_class_option_compendium_public_read" on public.threepp_class_option_compendium for select to anon, authenticated using (true);
create policy "threepp_class_option_compendium_service_write" on public.threepp_class_option_compendium for all to service_role using (true) with check (true);


create table if not exists public.oath_compendium (
  slug text primary key,
  "name" text,
  "oath_points" text,
  "oath" text,
  "defiance_penalty" text,
  "atonement" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("oath",'') || ' ' || coalesce("atonement",''))) stored
);
create index if not exists oath_compendium_search_idx on public.oath_compendium using gin (search);
alter table public.oath_compendium enable row level security;
create policy "oath_compendium_public_read" on public.oath_compendium for select to anon, authenticated using (true);
create policy "oath_compendium_service_write" on public.oath_compendium for all to service_role using (true) with check (true);


create table if not exists public.oath_boon_compendium (
  slug text primary key,
  "name" text,
  "oath_point_cost" text,
  "type" text,
  "description" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("type",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists oath_boon_compendium_search_idx on public.oath_boon_compendium using gin (search);
alter table public.oath_boon_compendium enable row level security;
create policy "oath_boon_compendium_public_read" on public.oath_boon_compendium for select to anon, authenticated using (true);
create policy "oath_boon_compendium_service_write" on public.oath_boon_compendium for all to service_role using (true) with check (true);


create table if not exists public.threepp_drawback_compendium (
  slug text primary key,
  "name" text,
  "category" text,
  "effect" text,
  "bonus_granted" text,
  "prerequisite" text,
  "description" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("category",'') || ' ' || coalesce("effect",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists threepp_drawback_compendium_search_idx on public.threepp_drawback_compendium using gin (search);
alter table public.threepp_drawback_compendium enable row level security;
create policy "threepp_drawback_compendium_public_read" on public.threepp_drawback_compendium for select to anon, authenticated using (true);
create policy "threepp_drawback_compendium_service_write" on public.threepp_drawback_compendium for all to service_role using (true) with check (true);


create table if not exists public.background_compendium (
  slug text primary key,
  "name" text,
  "type" text,
  "description" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("type",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists background_compendium_search_idx on public.background_compendium using gin (search);
alter table public.background_compendium enable row level security;
create policy "background_compendium_public_read" on public.background_compendium for select to anon, authenticated using (true);
create policy "background_compendium_service_write" on public.background_compendium for all to service_role using (true) with check (true);


create table if not exists public.occupation_compendium (
  slug text primary key,
  "name" text,
  "class_skills_or_benefit" text,
  "granted_feat" text,
  "description" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("class_skills_or_benefit",'') || ' ' || coalesce("granted_feat",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists occupation_compendium_search_idx on public.occupation_compendium using gin (search);
alter table public.occupation_compendium enable row level security;
create policy "occupation_compendium_public_read" on public.occupation_compendium for select to anon, authenticated using (true);
create policy "occupation_compendium_service_write" on public.occupation_compendium for all to service_role using (true) with check (true);


create table if not exists public.threepp_race_compendium (
  slug text primary key,
  "name" text,
  "system" text,
  "ability_modifiers" text,
  "size" text,
  "speed" text,
  "racial_traits" text,
  "description" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("system",'') || ' ' || coalesce("racial_traits",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists threepp_race_compendium_search_idx on public.threepp_race_compendium using gin (search);
alter table public.threepp_race_compendium enable row level security;
create policy "threepp_race_compendium_public_read" on public.threepp_race_compendium for select to anon, authenticated using (true);
create policy "threepp_race_compendium_service_write" on public.threepp_race_compendium for all to service_role using (true) with check (true);


create table if not exists public.threepp_racial_trait_compendium (
  slug text primary key,
  "name" text,
  "race" text,
  "system" text,
  "replaces" text,
  "description" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("race",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists threepp_racial_trait_compendium_search_idx on public.threepp_racial_trait_compendium using gin (search);
create index if not exists threepp_racial_trait_compendium_race_idx on public.threepp_racial_trait_compendium ("race");
alter table public.threepp_racial_trait_compendium enable row level security;
create policy "threepp_racial_trait_compendium_public_read" on public.threepp_racial_trait_compendium for select to anon, authenticated using (true);
create policy "threepp_racial_trait_compendium_service_write" on public.threepp_racial_trait_compendium for all to service_role using (true) with check (true);


create table if not exists public.threepp_trait_compendium (
  slug text primary key,
  "name" text,
  "type" text,
  "system" text,
  "description" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("type",'') || ' ' || coalesce("system",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists threepp_trait_compendium_search_idx on public.threepp_trait_compendium using gin (search);
alter table public.threepp_trait_compendium enable row level security;
create policy "threepp_trait_compendium_public_read" on public.threepp_trait_compendium for select to anon, authenticated using (true);
create policy "threepp_trait_compendium_service_write" on public.threepp_trait_compendium for all to service_role using (true) with check (true);



-- 00XX_threepp_search_rpcs.sql  (generated by threepp.mjs rpc — migration-0026 pattern:
-- escape CTE + ILIKE substring WHERE + websearch FTS OR-branch; rank exact > prefix > substring > ts_rank)

create or replace function public.search_psionic_power_compendium(p_query text default '', p_limit int default 60)
returns setof public.psionic_power_compendium language sql stable set search_path = public as $func$
  with q as (
    select replace(replace(replace(coalesce(p_query, ''), '\', '\\'), '%', '\%'), '_', '\_') as esc
  )
  select t.* from public.psionic_power_compendium t, q
  where coalesce(p_query, '') = ''
     or t."name" ilike '%' || q.esc || '%'
     or t.search @@ websearch_to_tsquery('english', p_query)
  order by
    case
      when coalesce(p_query, '') = '' then 3
      when lower(t."name") = lower(p_query) then 0
      when t."name" ilike q.esc || '%' then 1
      when t."name" ilike '%' || q.esc || '%' then 2
      else 3
    end,
    case when coalesce(p_query, '') = '' then 0 else ts_rank(t.search, websearch_to_tsquery('english', p_query)) end desc,
    t."name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_pow_discipline_compendium(p_query text default '', p_limit int default 60)
returns setof public.pow_discipline_compendium language sql stable set search_path = public as $func$
  with q as (
    select replace(replace(replace(coalesce(p_query, ''), '\', '\\'), '%', '\%'), '_', '\_') as esc
  )
  select t.* from public.pow_discipline_compendium t, q
  where coalesce(p_query, '') = ''
     or t."name" ilike '%' || q.esc || '%'
     or t.search @@ websearch_to_tsquery('english', p_query)
  order by
    case
      when coalesce(p_query, '') = '' then 3
      when lower(t."name") = lower(p_query) then 0
      when t."name" ilike q.esc || '%' then 1
      when t."name" ilike '%' || q.esc || '%' then 2
      else 3
    end,
    case when coalesce(p_query, '') = '' then 0 else ts_rank(t.search, websearch_to_tsquery('english', p_query)) end desc,
    t."name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_pow_maneuver_compendium(p_query text default '', p_limit int default 60)
returns setof public.pow_maneuver_compendium language sql stable set search_path = public as $func$
  with q as (
    select replace(replace(replace(coalesce(p_query, ''), '\', '\\'), '%', '\%'), '_', '\_') as esc
  )
  select t.* from public.pow_maneuver_compendium t, q
  where coalesce(p_query, '') = ''
     or t."name" ilike '%' || q.esc || '%'
     or t.search @@ websearch_to_tsquery('english', p_query)
  order by
    case
      when coalesce(p_query, '') = '' then 3
      when lower(t."name") = lower(p_query) then 0
      when t."name" ilike q.esc || '%' then 1
      when t."name" ilike '%' || q.esc || '%' then 2
      else 3
    end,
    case when coalesce(p_query, '') = '' then 0 else ts_rank(t.search, websearch_to_tsquery('english', p_query)) end desc,
    t."name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_akashic_veil_compendium(p_query text default '', p_limit int default 60)
returns setof public.akashic_veil_compendium language sql stable set search_path = public as $func$
  with q as (
    select replace(replace(replace(coalesce(p_query, ''), '\', '\\'), '%', '\%'), '_', '\_') as esc
  )
  select t.* from public.akashic_veil_compendium t, q
  where coalesce(p_query, '') = ''
     or t."name" ilike '%' || q.esc || '%'
     or t.search @@ websearch_to_tsquery('english', p_query)
  order by
    case
      when coalesce(p_query, '') = '' then 3
      when lower(t."name") = lower(p_query) then 0
      when t."name" ilike q.esc || '%' then 1
      when t."name" ilike '%' || q.esc || '%' then 2
      else 3
    end,
    case when coalesce(p_query, '') = '' then 0 else ts_rank(t.search, websearch_to_tsquery('english', p_query)) end desc,
    t."name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_threepp_feat_compendium(p_query text default '', p_limit int default 60)
returns setof public.threepp_feat_compendium language sql stable set search_path = public as $func$
  with q as (
    select replace(replace(replace(coalesce(p_query, ''), '\', '\\'), '%', '\%'), '_', '\_') as esc
  )
  select t.* from public.threepp_feat_compendium t, q
  where coalesce(p_query, '') = ''
     or t."name" ilike '%' || q.esc || '%'
     or t.search @@ websearch_to_tsquery('english', p_query)
  order by
    case
      when coalesce(p_query, '') = '' then 3
      when lower(t."name") = lower(p_query) then 0
      when t."name" ilike q.esc || '%' then 1
      when t."name" ilike '%' || q.esc || '%' then 2
      else 3
    end,
    case when coalesce(p_query, '') = '' then 0 else ts_rank(t.search, websearch_to_tsquery('english', p_query)) end desc,
    t."name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_threepp_class_compendium(p_query text default '', p_limit int default 60)
returns setof public.threepp_class_compendium language sql stable set search_path = public as $func$
  with q as (
    select replace(replace(replace(coalesce(p_query, ''), '\', '\\'), '%', '\%'), '_', '\_') as esc
  )
  select t.* from public.threepp_class_compendium t, q
  where coalesce(p_query, '') = ''
     or t."name" ilike '%' || q.esc || '%'
     or t.search @@ websearch_to_tsquery('english', p_query)
  order by
    case
      when coalesce(p_query, '') = '' then 3
      when lower(t."name") = lower(p_query) then 0
      when t."name" ilike q.esc || '%' then 1
      when t."name" ilike '%' || q.esc || '%' then 2
      else 3
    end,
    case when coalesce(p_query, '') = '' then 0 else ts_rank(t.search, websearch_to_tsquery('english', p_query)) end desc,
    t."name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_threepp_archetype_compendium(p_query text default '', p_limit int default 60)
returns setof public.threepp_archetype_compendium language sql stable set search_path = public as $func$
  with q as (
    select replace(replace(replace(coalesce(p_query, ''), '\', '\\'), '%', '\%'), '_', '\_') as esc
  )
  select t.* from public.threepp_archetype_compendium t, q
  where coalesce(p_query, '') = ''
     or t."name" ilike '%' || q.esc || '%'
     or t.search @@ websearch_to_tsquery('english', p_query)
  order by
    case
      when coalesce(p_query, '') = '' then 3
      when lower(t."name") = lower(p_query) then 0
      when t."name" ilike q.esc || '%' then 1
      when t."name" ilike '%' || q.esc || '%' then 2
      else 3
    end,
    case when coalesce(p_query, '') = '' then 0 else ts_rank(t.search, websearch_to_tsquery('english', p_query)) end desc,
    t."name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_threepp_class_option_compendium(p_query text default '', p_limit int default 60)
returns setof public.threepp_class_option_compendium language sql stable set search_path = public as $func$
  with q as (
    select replace(replace(replace(coalesce(p_query, ''), '\', '\\'), '%', '\%'), '_', '\_') as esc
  )
  select t.* from public.threepp_class_option_compendium t, q
  where coalesce(p_query, '') = ''
     or t."name" ilike '%' || q.esc || '%'
     or t.search @@ websearch_to_tsquery('english', p_query)
  order by
    case
      when coalesce(p_query, '') = '' then 3
      when lower(t."name") = lower(p_query) then 0
      when t."name" ilike q.esc || '%' then 1
      when t."name" ilike '%' || q.esc || '%' then 2
      else 3
    end,
    case when coalesce(p_query, '') = '' then 0 else ts_rank(t.search, websearch_to_tsquery('english', p_query)) end desc,
    t."name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_oath_compendium(p_query text default '', p_limit int default 60)
returns setof public.oath_compendium language sql stable set search_path = public as $func$
  with q as (
    select replace(replace(replace(coalesce(p_query, ''), '\', '\\'), '%', '\%'), '_', '\_') as esc
  )
  select t.* from public.oath_compendium t, q
  where coalesce(p_query, '') = ''
     or t."name" ilike '%' || q.esc || '%'
     or t.search @@ websearch_to_tsquery('english', p_query)
  order by
    case
      when coalesce(p_query, '') = '' then 3
      when lower(t."name") = lower(p_query) then 0
      when t."name" ilike q.esc || '%' then 1
      when t."name" ilike '%' || q.esc || '%' then 2
      else 3
    end,
    case when coalesce(p_query, '') = '' then 0 else ts_rank(t.search, websearch_to_tsquery('english', p_query)) end desc,
    t."name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_oath_boon_compendium(p_query text default '', p_limit int default 60)
returns setof public.oath_boon_compendium language sql stable set search_path = public as $func$
  with q as (
    select replace(replace(replace(coalesce(p_query, ''), '\', '\\'), '%', '\%'), '_', '\_') as esc
  )
  select t.* from public.oath_boon_compendium t, q
  where coalesce(p_query, '') = ''
     or t."name" ilike '%' || q.esc || '%'
     or t.search @@ websearch_to_tsquery('english', p_query)
  order by
    case
      when coalesce(p_query, '') = '' then 3
      when lower(t."name") = lower(p_query) then 0
      when t."name" ilike q.esc || '%' then 1
      when t."name" ilike '%' || q.esc || '%' then 2
      else 3
    end,
    case when coalesce(p_query, '') = '' then 0 else ts_rank(t.search, websearch_to_tsquery('english', p_query)) end desc,
    t."name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_threepp_drawback_compendium(p_query text default '', p_limit int default 60)
returns setof public.threepp_drawback_compendium language sql stable set search_path = public as $func$
  with q as (
    select replace(replace(replace(coalesce(p_query, ''), '\', '\\'), '%', '\%'), '_', '\_') as esc
  )
  select t.* from public.threepp_drawback_compendium t, q
  where coalesce(p_query, '') = ''
     or t."name" ilike '%' || q.esc || '%'
     or t.search @@ websearch_to_tsquery('english', p_query)
  order by
    case
      when coalesce(p_query, '') = '' then 3
      when lower(t."name") = lower(p_query) then 0
      when t."name" ilike q.esc || '%' then 1
      when t."name" ilike '%' || q.esc || '%' then 2
      else 3
    end,
    case when coalesce(p_query, '') = '' then 0 else ts_rank(t.search, websearch_to_tsquery('english', p_query)) end desc,
    t."name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_background_compendium(p_query text default '', p_limit int default 60)
returns setof public.background_compendium language sql stable set search_path = public as $func$
  with q as (
    select replace(replace(replace(coalesce(p_query, ''), '\', '\\'), '%', '\%'), '_', '\_') as esc
  )
  select t.* from public.background_compendium t, q
  where coalesce(p_query, '') = ''
     or t."name" ilike '%' || q.esc || '%'
     or t.search @@ websearch_to_tsquery('english', p_query)
  order by
    case
      when coalesce(p_query, '') = '' then 3
      when lower(t."name") = lower(p_query) then 0
      when t."name" ilike q.esc || '%' then 1
      when t."name" ilike '%' || q.esc || '%' then 2
      else 3
    end,
    case when coalesce(p_query, '') = '' then 0 else ts_rank(t.search, websearch_to_tsquery('english', p_query)) end desc,
    t."name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_occupation_compendium(p_query text default '', p_limit int default 60)
returns setof public.occupation_compendium language sql stable set search_path = public as $func$
  with q as (
    select replace(replace(replace(coalesce(p_query, ''), '\', '\\'), '%', '\%'), '_', '\_') as esc
  )
  select t.* from public.occupation_compendium t, q
  where coalesce(p_query, '') = ''
     or t."name" ilike '%' || q.esc || '%'
     or t.search @@ websearch_to_tsquery('english', p_query)
  order by
    case
      when coalesce(p_query, '') = '' then 3
      when lower(t."name") = lower(p_query) then 0
      when t."name" ilike q.esc || '%' then 1
      when t."name" ilike '%' || q.esc || '%' then 2
      else 3
    end,
    case when coalesce(p_query, '') = '' then 0 else ts_rank(t.search, websearch_to_tsquery('english', p_query)) end desc,
    t."name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_threepp_race_compendium(p_query text default '', p_limit int default 60)
returns setof public.threepp_race_compendium language sql stable set search_path = public as $func$
  with q as (
    select replace(replace(replace(coalesce(p_query, ''), '\', '\\'), '%', '\%'), '_', '\_') as esc
  )
  select t.* from public.threepp_race_compendium t, q
  where coalesce(p_query, '') = ''
     or t."name" ilike '%' || q.esc || '%'
     or t.search @@ websearch_to_tsquery('english', p_query)
  order by
    case
      when coalesce(p_query, '') = '' then 3
      when lower(t."name") = lower(p_query) then 0
      when t."name" ilike q.esc || '%' then 1
      when t."name" ilike '%' || q.esc || '%' then 2
      else 3
    end,
    case when coalesce(p_query, '') = '' then 0 else ts_rank(t.search, websearch_to_tsquery('english', p_query)) end desc,
    t."name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_threepp_racial_trait_compendium(p_query text default '', p_limit int default 60)
returns setof public.threepp_racial_trait_compendium language sql stable set search_path = public as $func$
  with q as (
    select replace(replace(replace(coalesce(p_query, ''), '\', '\\'), '%', '\%'), '_', '\_') as esc
  )
  select t.* from public.threepp_racial_trait_compendium t, q
  where coalesce(p_query, '') = ''
     or t."name" ilike '%' || q.esc || '%'
     or t.search @@ websearch_to_tsquery('english', p_query)
  order by
    case
      when coalesce(p_query, '') = '' then 3
      when lower(t."name") = lower(p_query) then 0
      when t."name" ilike q.esc || '%' then 1
      when t."name" ilike '%' || q.esc || '%' then 2
      else 3
    end,
    case when coalesce(p_query, '') = '' then 0 else ts_rank(t.search, websearch_to_tsquery('english', p_query)) end desc,
    t."name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_threepp_trait_compendium(p_query text default '', p_limit int default 60)
returns setof public.threepp_trait_compendium language sql stable set search_path = public as $func$
  with q as (
    select replace(replace(replace(coalesce(p_query, ''), '\', '\\'), '%', '\%'), '_', '\_') as esc
  )
  select t.* from public.threepp_trait_compendium t, q
  where coalesce(p_query, '') = ''
     or t."name" ilike '%' || q.esc || '%'
     or t.search @@ websearch_to_tsquery('english', p_query)
  order by
    case
      when coalesce(p_query, '') = '' then 3
      when lower(t."name") = lower(p_query) then 0
      when t."name" ilike q.esc || '%' then 1
      when t."name" ilike '%' || q.esc || '%' then 2
      else 3
    end,
    case when coalesce(p_query, '') = '' then 0 else ts_rank(t.search, websearch_to_tsquery('english', p_query)) end desc,
    t."name"
  limit greatest(1, least(p_limit, 200));
$func$;


-- 00XX_threepp_grants.sql  (generated by threepp.mjs grants — explicit grants)

grant select on table public.psionic_power_compendium to anon, authenticated;
grant select on table public.psionic_power_class_level to anon, authenticated;
grant select on table public.pow_discipline_compendium to anon, authenticated;
grant select on table public.pow_maneuver_compendium to anon, authenticated;
grant select on table public.akashic_veil_compendium to anon, authenticated;
grant select on table public.akashic_veil_class_list to anon, authenticated;
grant select on table public.threepp_feat_compendium to anon, authenticated;
grant select on table public.threepp_class_compendium to anon, authenticated;
grant select on table public.threepp_archetype_compendium to anon, authenticated;
grant select on table public.threepp_class_option_compendium to anon, authenticated;
grant select on table public.oath_compendium to anon, authenticated;
grant select on table public.oath_boon_compendium to anon, authenticated;
grant select on table public.threepp_drawback_compendium to anon, authenticated;
grant select on table public.background_compendium to anon, authenticated;
grant select on table public.occupation_compendium to anon, authenticated;
grant select on table public.threepp_race_compendium to anon, authenticated;
grant select on table public.threepp_racial_trait_compendium to anon, authenticated;
grant select on table public.threepp_trait_compendium to anon, authenticated;

grant execute on function public.search_psionic_power_compendium(text, int) to anon, authenticated;
grant execute on function public.search_pow_discipline_compendium(text, int) to anon, authenticated;
grant execute on function public.search_pow_maneuver_compendium(text, int) to anon, authenticated;
grant execute on function public.search_akashic_veil_compendium(text, int) to anon, authenticated;
grant execute on function public.search_threepp_feat_compendium(text, int) to anon, authenticated;
grant execute on function public.search_threepp_class_compendium(text, int) to anon, authenticated;
grant execute on function public.search_threepp_archetype_compendium(text, int) to anon, authenticated;
grant execute on function public.search_threepp_class_option_compendium(text, int) to anon, authenticated;
grant execute on function public.search_oath_compendium(text, int) to anon, authenticated;
grant execute on function public.search_oath_boon_compendium(text, int) to anon, authenticated;
grant execute on function public.search_threepp_drawback_compendium(text, int) to anon, authenticated;
grant execute on function public.search_background_compendium(text, int) to anon, authenticated;
grant execute on function public.search_occupation_compendium(text, int) to anon, authenticated;
grant execute on function public.search_threepp_race_compendium(text, int) to anon, authenticated;
grant execute on function public.search_threepp_racial_trait_compendium(text, int) to anon, authenticated;
grant execute on function public.search_threepp_trait_compendium(text, int) to anon, authenticated;
