-- 0021_pfcore_compendium.sql  (generated by pfcore.mjs — DO NOT hand-edit; regenerate)

create table if not exists public.feat_compendium (
  slug text primary key,
  "name" text,
  "types" text,
  "source" text,
  "description" text,
  "prerequisites" text,
  "benefit" text,
  "normal" text,
  "special" text,
  "mythic" text,
  "combat_trick" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("types",'') || ' ' || coalesce("description",'') || ' ' || coalesce("benefit",'') || ' ' || coalesce("prerequisites",''))) stored
);
create index if not exists feat_compendium_search_idx on public.feat_compendium using gin (search);
alter table public.feat_compendium enable row level security;
create policy "feat_compendium_public_read" on public.feat_compendium for select using (true);
create policy "feat_compendium_service_write" on public.feat_compendium for all to service_role using (true) with check (true);
create or replace function public.search_feat_compendium(p_query text default '', p_limit int default 60)
returns setof public.feat_compendium language sql stable set search_path = public as $func$
  select * from public.feat_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "name"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.feat_prerequisite (
  slug text primary key,
  "feat" text,
  "req_type" text,
  "req_value" text
);
create index if not exists feat_prerequisite_feat_idx on public.feat_prerequisite ("feat");
alter table public.feat_prerequisite enable row level security;
create policy "feat_prerequisite_public_read" on public.feat_prerequisite for select using (true);
create policy "feat_prerequisite_service_write" on public.feat_prerequisite for all to service_role using (true) with check (true);


create table if not exists public.feat_effect (
  slug text primary key,
  "feat" text,
  "target" text,
  "op" text,
  "value_or_formula" text,
  "bonus_type" text,
  "notes" text
);
create index if not exists feat_effect_feat_idx on public.feat_effect ("feat");
alter table public.feat_effect enable row level security;
create policy "feat_effect_public_read" on public.feat_effect for select using (true);
create policy "feat_effect_service_write" on public.feat_effect for all to service_role using (true) with check (true);


create table if not exists public.trait_compendium (
  slug text primary key,
  "name" text,
  "type" text,
  "category" text,
  "source" text,
  "requirements" text,
  "description" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("type",'') || ' ' || coalesce("category",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists trait_compendium_search_idx on public.trait_compendium using gin (search);
alter table public.trait_compendium enable row level security;
create policy "trait_compendium_public_read" on public.trait_compendium for select using (true);
create policy "trait_compendium_service_write" on public.trait_compendium for all to service_role using (true) with check (true);
create or replace function public.search_trait_compendium(p_query text default '', p_limit int default 60)
returns setof public.trait_compendium language sql stable set search_path = public as $func$
  select * from public.trait_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "name"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.drawback_compendium (
  slug text primary key,
  "name" text,
  "source" text,
  "requirements" text,
  "description" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists drawback_compendium_search_idx on public.drawback_compendium using gin (search);
alter table public.drawback_compendium enable row level security;
create policy "drawback_compendium_public_read" on public.drawback_compendium for select using (true);
create policy "drawback_compendium_service_write" on public.drawback_compendium for all to service_role using (true) with check (true);
create or replace function public.search_drawback_compendium(p_query text default '', p_limit int default 60)
returns setof public.drawback_compendium language sql stable set search_path = public as $func$
  select * from public.drawback_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "name"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.class_compendium (
  slug text primary key,
  "name" text,
  "category" text,
  "source" text,
  "hit_die" text,
  "alignment" text,
  "role" text,
  "starting_wealth" text,
  "class_skills" text,
  "skill_points_per_level" text,
  "proficiencies" text,
  "description" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("description",'') || ' ' || coalesce("role",''))) stored
);
create index if not exists class_compendium_search_idx on public.class_compendium using gin (search);
alter table public.class_compendium enable row level security;
create policy "class_compendium_public_read" on public.class_compendium for select using (true);
create policy "class_compendium_service_write" on public.class_compendium for all to service_role using (true) with check (true);
create or replace function public.search_class_compendium(p_query text default '', p_limit int default 60)
returns setof public.class_compendium language sql stable set search_path = public as $func$
  select * from public.class_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "name"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.class_progression (
  slug text primary key,
  "class" text,
  "json_data" jsonb
);
create index if not exists class_progression_class_idx on public.class_progression ("class");
alter table public.class_progression enable row level security;
create policy "class_progression_public_read" on public.class_progression for select using (true);
create policy "class_progression_service_write" on public.class_progression for all to service_role using (true) with check (true);


create table if not exists public.class_feature_compendium (
  slug text primary key,
  "class" text,
  "category" text,
  "feature" text,
  "type" text,
  "level" text,
  "description" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("feature",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists class_feature_compendium_search_idx on public.class_feature_compendium using gin (search);
create index if not exists class_feature_compendium_class_idx on public.class_feature_compendium ("class");
alter table public.class_feature_compendium enable row level security;
create policy "class_feature_compendium_public_read" on public.class_feature_compendium for select using (true);
create policy "class_feature_compendium_service_write" on public.class_feature_compendium for all to service_role using (true) with check (true);
create or replace function public.search_class_feature_compendium(p_query text default '', p_limit int default 60)
returns setof public.class_feature_compendium language sql stable set search_path = public as $func$
  select * from public.class_feature_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "feature"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.class_option_compendium (
  slug text primary key,
  "class" text,
  "option_type" text,
  "name" text,
  "subtype" text,
  "group" text,
  "source" text,
  "description" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("description",'') || ' ' || coalesce("option_type",''))) stored
);
create index if not exists class_option_compendium_search_idx on public.class_option_compendium using gin (search);
create index if not exists class_option_compendium_class_idx on public.class_option_compendium ("class");
alter table public.class_option_compendium enable row level security;
create policy "class_option_compendium_public_read" on public.class_option_compendium for select using (true);
create policy "class_option_compendium_service_write" on public.class_option_compendium for all to service_role using (true) with check (true);
create or replace function public.search_class_option_compendium(p_query text default '', p_limit int default 60)
returns setof public.class_option_compendium language sql stable set search_path = public as $func$
  select * from public.class_option_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "name"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.feature_effect (
  slug text primary key,
  "class" text,
  "feature" text,
  "target" text,
  "op" text,
  "value_or_formula" text,
  "bonus_type" text,
  "notes" text
);
create index if not exists feature_effect_class_idx on public.feature_effect ("class");
alter table public.feature_effect enable row level security;
create policy "feature_effect_public_read" on public.feature_effect for select using (true);
create policy "feature_effect_service_write" on public.feature_effect for all to service_role using (true) with check (true);


create table if not exists public.archetype_compendium (
  slug text primary key,
  "name" text,
  "class" text,
  "source" text,
  "description" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("class",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists archetype_compendium_search_idx on public.archetype_compendium using gin (search);
create index if not exists archetype_compendium_class_idx on public.archetype_compendium ("class");
alter table public.archetype_compendium enable row level security;
create policy "archetype_compendium_public_read" on public.archetype_compendium for select using (true);
create policy "archetype_compendium_service_write" on public.archetype_compendium for all to service_role using (true) with check (true);
create or replace function public.search_archetype_compendium(p_query text default '', p_limit int default 60)
returns setof public.archetype_compendium language sql stable set search_path = public as $func$
  select * from public.archetype_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "name"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.archetype_feature_compendium (
  slug text primary key,
  "archetype" text,
  "class" text,
  "feature" text,
  "type" text,
  "level" text,
  "replaces" text,
  "text" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("feature",'') || ' ' || coalesce("text",''))) stored
);
create index if not exists archetype_feature_compendium_search_idx on public.archetype_feature_compendium using gin (search);
create index if not exists archetype_feature_compendium_archetype_idx on public.archetype_feature_compendium ("archetype");
alter table public.archetype_feature_compendium enable row level security;
create policy "archetype_feature_compendium_public_read" on public.archetype_feature_compendium for select using (true);
create policy "archetype_feature_compendium_service_write" on public.archetype_feature_compendium for all to service_role using (true) with check (true);
create or replace function public.search_archetype_feature_compendium(p_query text default '', p_limit int default 60)
returns setof public.archetype_feature_compendium language sql stable set search_path = public as $func$
  select * from public.archetype_feature_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "feature"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.prestige_class_compendium (
  slug text primary key,
  "name" text,
  "source" text,
  "hit_die" text,
  "alignment" text,
  "role" text,
  "requirements" text,
  "description" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("description",'') || ' ' || coalesce("requirements",''))) stored
);
create index if not exists prestige_class_compendium_search_idx on public.prestige_class_compendium using gin (search);
alter table public.prestige_class_compendium enable row level security;
create policy "prestige_class_compendium_public_read" on public.prestige_class_compendium for select using (true);
create policy "prestige_class_compendium_service_write" on public.prestige_class_compendium for all to service_role using (true) with check (true);
create or replace function public.search_prestige_class_compendium(p_query text default '', p_limit int default 60)
returns setof public.prestige_class_compendium language sql stable set search_path = public as $func$
  select * from public.prestige_class_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "name"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.prestige_progression (
  slug text primary key,
  "class" text,
  "json_data" jsonb
);
create index if not exists prestige_progression_class_idx on public.prestige_progression ("class");
alter table public.prestige_progression enable row level security;
create policy "prestige_progression_public_read" on public.prestige_progression for select using (true);
create policy "prestige_progression_service_write" on public.prestige_progression for all to service_role using (true) with check (true);


create table if not exists public.race_compendium (
  slug text primary key,
  "name" text,
  "category" text,
  "source" text,
  "details" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("details",''))) stored
);
create index if not exists race_compendium_search_idx on public.race_compendium using gin (search);
alter table public.race_compendium enable row level security;
create policy "race_compendium_public_read" on public.race_compendium for select using (true);
create policy "race_compendium_service_write" on public.race_compendium for all to service_role using (true) with check (true);
create or replace function public.search_race_compendium(p_query text default '', p_limit int default 60)
returns setof public.race_compendium language sql stable set search_path = public as $func$
  select * from public.race_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "name"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.race_trait_compendium (
  slug text primary key,
  "race" text,
  "category" text,
  "source" text,
  "ability_modifiers" text,
  "size" text,
  "speed" text,
  "standard_traits" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("race",'') || ' ' || coalesce("standard_traits",''))) stored
);
create index if not exists race_trait_compendium_search_idx on public.race_trait_compendium using gin (search);
create index if not exists race_trait_compendium_race_idx on public.race_trait_compendium ("race");
alter table public.race_trait_compendium enable row level security;
create policy "race_trait_compendium_public_read" on public.race_trait_compendium for select using (true);
create policy "race_trait_compendium_service_write" on public.race_trait_compendium for all to service_role using (true) with check (true);
create or replace function public.search_race_trait_compendium(p_query text default '', p_limit int default 60)
returns setof public.race_trait_compendium language sql stable set search_path = public as $func$
  select * from public.race_trait_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "race"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.alternate_racial_trait_compendium (
  slug text primary key,
  "race" text,
  "trait_name" text,
  "replaces" text,
  "source" text,
  "description" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("trait_name",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists alternate_racial_trait_compendium_search_idx on public.alternate_racial_trait_compendium using gin (search);
create index if not exists alternate_racial_trait_compendium_race_idx on public.alternate_racial_trait_compendium ("race");
alter table public.alternate_racial_trait_compendium enable row level security;
create policy "alternate_racial_trait_compendium_public_read" on public.alternate_racial_trait_compendium for select using (true);
create policy "alternate_racial_trait_compendium_service_write" on public.alternate_racial_trait_compendium for all to service_role using (true) with check (true);
create or replace function public.search_alternate_racial_trait_compendium(p_query text default '', p_limit int default 60)
returns setof public.alternate_racial_trait_compendium language sql stable set search_path = public as $func$
  select * from public.alternate_racial_trait_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "trait_name"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.favored_class_option_compendium (
  slug text primary key,
  "race" text,
  "class" text,
  "benefit" text,
  "source" text,
  "url" text
);
create index if not exists favored_class_option_compendium_race_idx on public.favored_class_option_compendium ("race");
alter table public.favored_class_option_compendium enable row level security;
create policy "favored_class_option_compendium_public_read" on public.favored_class_option_compendium for select using (true);
create policy "favored_class_option_compendium_service_write" on public.favored_class_option_compendium for all to service_role using (true) with check (true);


create table if not exists public.mythic_path_compendium (
  slug text primary key,
  "name" text,
  "source" text,
  "description" text,
  "json_data" jsonb,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists mythic_path_compendium_search_idx on public.mythic_path_compendium using gin (search);
alter table public.mythic_path_compendium enable row level security;
create policy "mythic_path_compendium_public_read" on public.mythic_path_compendium for select using (true);
create policy "mythic_path_compendium_service_write" on public.mythic_path_compendium for all to service_role using (true) with check (true);
create or replace function public.search_mythic_path_compendium(p_query text default '', p_limit int default 60)
returns setof public.mythic_path_compendium language sql stable set search_path = public as $func$
  select * from public.mythic_path_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "name"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.mythic_path_ability_compendium (
  slug text primary key,
  "path" text,
  "name" text,
  "type" text,
  "source" text,
  "description" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists mythic_path_ability_compendium_search_idx on public.mythic_path_ability_compendium using gin (search);
create index if not exists mythic_path_ability_compendium_path_idx on public.mythic_path_ability_compendium ("path");
alter table public.mythic_path_ability_compendium enable row level security;
create policy "mythic_path_ability_compendium_public_read" on public.mythic_path_ability_compendium for select using (true);
create policy "mythic_path_ability_compendium_service_write" on public.mythic_path_ability_compendium for all to service_role using (true) with check (true);
create or replace function public.search_mythic_path_ability_compendium(p_query text default '', p_limit int default 60)
returns setof public.mythic_path_ability_compendium language sql stable set search_path = public as $func$
  select * from public.mythic_path_ability_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "name"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.mythic_spell_augment (
  slug text primary key,
  "name" text,
  "school" text,
  "subschool" text,
  "descriptors" text,
  "level" text,
  "casting_time" text,
  "components" text,
  "range" text,
  "target" text,
  "area" text,
  "effect" text,
  "duration" text,
  "saving_throw" text,
  "spell_resistance" text,
  "description" text,
  "mythic" text,
  "source" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("description",'') || ' ' || coalesce("mythic",''))) stored
);
create index if not exists mythic_spell_augment_search_idx on public.mythic_spell_augment using gin (search);
alter table public.mythic_spell_augment enable row level security;
create policy "mythic_spell_augment_public_read" on public.mythic_spell_augment for select using (true);
create policy "mythic_spell_augment_service_write" on public.mythic_spell_augment for all to service_role using (true) with check (true);
create or replace function public.search_mythic_spell_augment(p_query text default '', p_limit int default 60)
returns setof public.mythic_spell_augment language sql stable set search_path = public as $func$
  select * from public.mythic_spell_augment
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "name"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.animal_companion_compendium (
  slug text primary key,
  "name" text,
  "category" text,
  "source" text,
  "size" text,
  "speed" text,
  "ac" text,
  "attack" text,
  "ability_scores" text,
  "special_qualities" text,
  "starting_stats" text,
  "advancement" text,
  "flavor" text,
  "monster_url" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("special_qualities",'') || ' ' || coalesce("flavor",''))) stored
);
create index if not exists animal_companion_compendium_search_idx on public.animal_companion_compendium using gin (search);
alter table public.animal_companion_compendium enable row level security;
create policy "animal_companion_compendium_public_read" on public.animal_companion_compendium for select using (true);
create policy "animal_companion_compendium_service_write" on public.animal_companion_compendium for all to service_role using (true) with check (true);
create or replace function public.search_animal_companion_compendium(p_query text default '', p_limit int default 60)
returns setof public.animal_companion_compendium language sql stable set search_path = public as $func$
  select * from public.animal_companion_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "name"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.familiar_compendium (
  slug text primary key,
  "name" text,
  "granted_ability" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("granted_ability",''))) stored
);
create index if not exists familiar_compendium_search_idx on public.familiar_compendium using gin (search);
alter table public.familiar_compendium enable row level security;
create policy "familiar_compendium_public_read" on public.familiar_compendium for select using (true);
create policy "familiar_compendium_service_write" on public.familiar_compendium for all to service_role using (true) with check (true);
create or replace function public.search_familiar_compendium(p_query text default '', p_limit int default 60)
returns setof public.familiar_compendium language sql stable set search_path = public as $func$
  select * from public.familiar_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "name"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.eidolon_base_form_compendium (
  slug text primary key,
  "name" text,
  "source" text,
  "description" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists eidolon_base_form_compendium_search_idx on public.eidolon_base_form_compendium using gin (search);
alter table public.eidolon_base_form_compendium enable row level security;
create policy "eidolon_base_form_compendium_public_read" on public.eidolon_base_form_compendium for select using (true);
create policy "eidolon_base_form_compendium_service_write" on public.eidolon_base_form_compendium for all to service_role using (true) with check (true);
create or replace function public.search_eidolon_base_form_compendium(p_query text default '', p_limit int default 60)
returns setof public.eidolon_base_form_compendium language sql stable set search_path = public as $func$
  select * from public.eidolon_base_form_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "name"
  limit greatest(1, least(p_limit, 200));
$func$;


create table if not exists public.eidolon_evolution_compendium (
  slug text primary key,
  "name" text,
  "cost" text,
  "source" text,
  "description" text,
  "url" text,
  search tsvector generated always as (to_tsvector('english', coalesce("name",'') || ' ' || coalesce("description",''))) stored
);
create index if not exists eidolon_evolution_compendium_search_idx on public.eidolon_evolution_compendium using gin (search);
alter table public.eidolon_evolution_compendium enable row level security;
create policy "eidolon_evolution_compendium_public_read" on public.eidolon_evolution_compendium for select using (true);
create policy "eidolon_evolution_compendium_service_write" on public.eidolon_evolution_compendium for all to service_role using (true) with check (true);
create or replace function public.search_eidolon_evolution_compendium(p_query text default '', p_limit int default 60)
returns setof public.eidolon_evolution_compendium language sql stable set search_path = public as $func$
  select * from public.eidolon_evolution_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc, "name"
  limit greatest(1, least(p_limit, 200));
$func$;


