-- 0022_pfcore_search_rank.sql  (generated by pfcore.mjs — exact/prefix-boosted ranking)

create or replace function public.search_feat_compendium(p_query text default '', p_limit int default 60)
returns setof public.feat_compendium language sql stable set search_path = public as $func$
  select * from public.feat_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("name") = lower(p_query) then 0 when "name" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_trait_compendium(p_query text default '', p_limit int default 60)
returns setof public.trait_compendium language sql stable set search_path = public as $func$
  select * from public.trait_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("name") = lower(p_query) then 0 when "name" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_drawback_compendium(p_query text default '', p_limit int default 60)
returns setof public.drawback_compendium language sql stable set search_path = public as $func$
  select * from public.drawback_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("name") = lower(p_query) then 0 when "name" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_class_compendium(p_query text default '', p_limit int default 60)
returns setof public.class_compendium language sql stable set search_path = public as $func$
  select * from public.class_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("name") = lower(p_query) then 0 when "name" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_class_feature_compendium(p_query text default '', p_limit int default 60)
returns setof public.class_feature_compendium language sql stable set search_path = public as $func$
  select * from public.class_feature_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("feature") = lower(p_query) then 0 when "feature" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "feature"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_class_option_compendium(p_query text default '', p_limit int default 60)
returns setof public.class_option_compendium language sql stable set search_path = public as $func$
  select * from public.class_option_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("name") = lower(p_query) then 0 when "name" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_archetype_compendium(p_query text default '', p_limit int default 60)
returns setof public.archetype_compendium language sql stable set search_path = public as $func$
  select * from public.archetype_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("name") = lower(p_query) then 0 when "name" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_archetype_feature_compendium(p_query text default '', p_limit int default 60)
returns setof public.archetype_feature_compendium language sql stable set search_path = public as $func$
  select * from public.archetype_feature_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("feature") = lower(p_query) then 0 when "feature" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "feature"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_prestige_class_compendium(p_query text default '', p_limit int default 60)
returns setof public.prestige_class_compendium language sql stable set search_path = public as $func$
  select * from public.prestige_class_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("name") = lower(p_query) then 0 when "name" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_race_compendium(p_query text default '', p_limit int default 60)
returns setof public.race_compendium language sql stable set search_path = public as $func$
  select * from public.race_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("name") = lower(p_query) then 0 when "name" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_race_trait_compendium(p_query text default '', p_limit int default 60)
returns setof public.race_trait_compendium language sql stable set search_path = public as $func$
  select * from public.race_trait_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("race") = lower(p_query) then 0 when "race" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "race"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_alternate_racial_trait_compendium(p_query text default '', p_limit int default 60)
returns setof public.alternate_racial_trait_compendium language sql stable set search_path = public as $func$
  select * from public.alternate_racial_trait_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("trait_name") = lower(p_query) then 0 when "trait_name" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "trait_name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_mythic_path_compendium(p_query text default '', p_limit int default 60)
returns setof public.mythic_path_compendium language sql stable set search_path = public as $func$
  select * from public.mythic_path_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("name") = lower(p_query) then 0 when "name" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_mythic_path_ability_compendium(p_query text default '', p_limit int default 60)
returns setof public.mythic_path_ability_compendium language sql stable set search_path = public as $func$
  select * from public.mythic_path_ability_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("name") = lower(p_query) then 0 when "name" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_mythic_spell_augment(p_query text default '', p_limit int default 60)
returns setof public.mythic_spell_augment language sql stable set search_path = public as $func$
  select * from public.mythic_spell_augment
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("name") = lower(p_query) then 0 when "name" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_animal_companion_compendium(p_query text default '', p_limit int default 60)
returns setof public.animal_companion_compendium language sql stable set search_path = public as $func$
  select * from public.animal_companion_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("name") = lower(p_query) then 0 when "name" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_familiar_compendium(p_query text default '', p_limit int default 60)
returns setof public.familiar_compendium language sql stable set search_path = public as $func$
  select * from public.familiar_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("name") = lower(p_query) then 0 when "name" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_eidolon_base_form_compendium(p_query text default '', p_limit int default 60)
returns setof public.eidolon_base_form_compendium language sql stable set search_path = public as $func$
  select * from public.eidolon_base_form_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("name") = lower(p_query) then 0 when "name" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "name"
  limit greatest(1, least(p_limit, 200));
$func$;

create or replace function public.search_eidolon_evolution_compendium(p_query text default '', p_limit int default 60)
returns setof public.eidolon_evolution_compendium language sql stable set search_path = public as $func$
  select * from public.eidolon_evolution_compendium
  where p_query = '' or search @@ websearch_to_tsquery('english', p_query)
  order by
    case when p_query = '' then 2 when lower("name") = lower(p_query) then 0 when "name" ilike p_query || '%' then 1 else 2 end,
    case when p_query = '' then 0 else ts_rank(search, websearch_to_tsquery('english', p_query)) end desc,
    "name"
  limit greatest(1, least(p_limit, 200));
$func$;

