-- 0024_pfcore_grants.sql  (generated by pfcore.mjs — explicit RPC execute grants)

grant execute on function public.search_feat_compendium(text, int) to anon, authenticated;
grant execute on function public.search_trait_compendium(text, int) to anon, authenticated;
grant execute on function public.search_drawback_compendium(text, int) to anon, authenticated;
grant execute on function public.search_class_compendium(text, int) to anon, authenticated;
grant execute on function public.search_class_feature_compendium(text, int) to anon, authenticated;
grant execute on function public.search_class_option_compendium(text, int) to anon, authenticated;
grant execute on function public.search_archetype_compendium(text, int) to anon, authenticated;
grant execute on function public.search_archetype_feature_compendium(text, int) to anon, authenticated;
grant execute on function public.search_prestige_class_compendium(text, int) to anon, authenticated;
grant execute on function public.search_race_compendium(text, int) to anon, authenticated;
grant execute on function public.search_race_trait_compendium(text, int) to anon, authenticated;
grant execute on function public.search_alternate_racial_trait_compendium(text, int) to anon, authenticated;
grant execute on function public.search_mythic_path_compendium(text, int) to anon, authenticated;
grant execute on function public.search_mythic_path_ability_compendium(text, int) to anon, authenticated;
grant execute on function public.search_mythic_spell_augment(text, int) to anon, authenticated;
grant execute on function public.search_animal_companion_compendium(text, int) to anon, authenticated;
grant execute on function public.search_familiar_compendium(text, int) to anon, authenticated;
grant execute on function public.search_eidolon_base_form_compendium(text, int) to anon, authenticated;
grant execute on function public.search_eidolon_evolution_compendium(text, int) to anon, authenticated;
grant execute on function public.compendium_distinct(text, text) to anon, authenticated;
